------STARTING PROCEDURE---------------------------------
--STEP 1. DROP ALL CONSTRAINTS AND TRUNCATE TABLES
ALTER PROCEDURE [dbo].[PRC_A10]
AS
BEGIN

ALTER TABLE FACTS
	DROP CONSTRAINT PK_FACTS,
		 CONSTRAINT FK_TIME,
		 CONSTRAINT FK_PILOT,
		 CONSTRAINT FK_AIRCRAFT
		 
ALTER TABLE AIRCRAFTDIM
	DROP CONSTRAINT PK_AIRCRAFTDIM

ALTER TABLE TIMEDIM
	DROP CONSTRAINT PK_TIMEDIM
	
ALTER TABLE PILOTDIM
	DROP CONSTRAINT PK_PILOTDIM

TRUNCATE TABLE AIRCRAFTDIM
TRUNCATE TABLE TIMEDIM
TRUNCATE TABLE PILOTDIM
TRUNCATE TABLE FACTS

--STEP 2. ADD CONSTRAINTS BACK TO POPULATE DIMENSION TABLES
ALTER TABLE AIRCRAFTDIM
	ADD CONSTRAINT PK_AIRCRAFTDIM PRIMARY KEY (AIRCRAFT_KEY)

ALTER TABLE TIMEDIM
	ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY (TIME_KEY)

ALTER TABLE PILOTDIM
	ADD CONSTRAINT PK_PILOTDIM PRIMARY KEY (PILOT_KEY)

ALTER TABLE FACTS
	ADD CONSTRAINT PK_FACTS PRIMARY KEY (TIME_KEY, PILOT_KEY, AIRCRAFT_KEY),
		CONSTRAINT FK_TIME FOREIGN KEY (TIME_KEY) REFERENCES TIMEDIM,
		CONSTRAINT FK_PILOT FOREIGN KEY (PILOT_KEY) REFERENCES PILOTDIM,
		CONSTRAINT FK_AIRCRAFT FOREIGN KEY (AIRCRAFT_KEY) REFERENCES AIRCRAFTDIM

INSERT INTO AIRCRAFTDIM
SELECT	* 
FROM	AIRCRAFT

INSERT INTO PILOTDIM
SELECT	DISTINCT P.EMP_NUM, E.EMP_LNAME, E.EMP_FNAME, P.PIL_LICENSE, P.PIL_RATINGS, P.PIL_MED_TYPE, P.PIL_MED_DATE, P.PIL_PT135_DATE
FROM	PILOT P INNER JOIN EMPLOYEE E ON E.EMP_NUM = P.EMP_NUM

INSERT INTO TIMEDIM
SELECT	DISTINCT CHAR_DATE, YEAR(CHAR_DATE), MONTH(CHAR_DATE)
FROM	CHARTER

--STEP 3. POPULATE STAGINGTABLE
CREATE TABLE STAGINGTABLE (
AC_NUMBER VARCHAR(5),
EMP_NUM INT,
CHAR_DATE DATETIME,
CHAR_DISTANCE float(8), 
CHAR_FUEL_GALLONS float(8), 
MOD_CHG_MILE float(8),
TIME_KEY INT DEFAULT NULL,
PILOT_KEY INT DEFAULT NULL,
AIRCRAFT_KEY INT DEFAULT NULL
);
--3.1
INSERT INTO STAGINGTABLE(AC_NUMBER, EMP_NUM, CHAR_DATE, CHAR_DISTANCE, CHAR_FUEL_GALLONS, MOD_CHG_MILE)
SELECT	A.AC_NUMBER, P.EMP_NUM, C.CHAR_DATE, 
		C.CHAR_DISTANCE, C.CHAR_FUEL_GALLONS, M.MOD_CHG_MILE
FROM	CHARTER C INNER JOIN CREW CR ON C.CHAR_TRIP = CR.CHAR_TRIP
		INNER JOIN PILOT P ON CR.EMP_NUM = P.EMP_NUM
		INNER JOIN AIRCRAFT A ON C.AC_NUMBER = A.AC_NUMBER
		INNER JOIN MODEL M ON M.MOD_CODE = A.MOD_CODE

--3.2
UPDATE	STAGINGTABLE
SET	TIME_KEY = T.TIME_KEY
FROM STAGINGTABLE S INNER JOIN TIMEDIM T ON S.CHAR_DATE = T.CHAR_DATE

UPDATE	STAGINGTABLE
SET	PILOT_KEY = P.PILOT_KEY
FROM STAGINGTABLE S INNER JOIN PILOTDIM P ON S.EMP_NUM = P.EMP_NUM

UPDATE	STAGINGTABLE
SET	AIRCRAFT_KEY = A.AIRCRAFT_KEY
FROM STAGINGTABLE S INNER JOIN AIRCRAFTDIM A ON S.AC_NUMBER = A.AC_NUMBER

--STEP 4. POPULATE FACT TABLE
INSERT INTO FACTS
SELECT	DISTINCT TIME_KEY, PILOT_KEY, AIRCRAFT_KEY, CHAR_DISTANCE, CHAR_FUEL_GALLONS, MOD_CHG_MILE
FROM	STAGINGTABLE

SELECT * FROM TIMEDIM
SELECT * FROM PILOTDIM
SELECT * FROM AIRCRAFTDIM
SELECT * FROM FACTS

DROP TABLE STAGINGTABLE
END
------------------FIN-------------------------------------------------

