--AUTHOR: MIKE KRIMM
--GROUP MEMBERS: AUSTIN BULLITT, ARIC HAMBLIN, JAYNA WINCHESTER
--CREATING DIMENSION TABLES-------------------------
CREATE TABLE AIRCRAFTDIM ( 
AIRCRAFT_KEY INT IDENTITY,
AC_NUMBER varchar(5), 
MOD_CODE varchar(10),
AC_TTAF float(8), 
AC_TTEL float(8), 
AC_TTER float(8) 
);

CREATE TABLE TIMEDIM (
TIME_KEY INT IDENTITY,
CHAR_DATE datetime, 
CHAR_YEAR INT,
CHAR_MONTH INT
);

CREATE TABLE PILOTDIM (
PILOT_KEY INT IDENTITY,
EMP_NUM INT,
EMP_LNAME VARCHAR(15),
EMP_FNAME VARCHAR(15),
PIL_LICENSE varchar(25), 
PIL_RATINGS varchar(25), 
PIL_MED_TYPE varchar(1), 
PIL_MED_DATE datetime, 
PIL_PT135_DATE datetime 
);

CREATE TABLE FACTS (
TIME_KEY INT NOT NULL,
PILOT_KEY INT NOT NULL,
AIRCRAFT_KEY INT NOT NULL,
CHAR_DISTANCE FLOAT(8),
CHAR_FUEL_GALLONS FLOAT(8),
MOD_CHG_MILE FLOAT(8)
);

ALTER TABLE AIRCRAFTDIM
	ADD CONSTRAINT PK_AIRCRAFTDIM PRIMARY KEY (AIRCRAFT_KEY)

ALTER TABLE TIMEDIM
	ADD CONSTRAINT PK_TIMEDIM PRIMARY KEY (TIME_KEY)

ALTER TABLE PILOTDIM
	ADD CONSTRAINT PK_PILOTDIM PRIMARY KEY (PILOT_KEY)

ALTER TABLE FACTS
	ADD CONSTRAINT PK_FACTS PRIMARY KEY (TIME_KEY, PILOT_KEY, AIRCRAFT_KEY),
		CONSTRAINT FK_TIME FOREIGN KEY (TIME_KEY) REFERENCES TIMEDIM,
		CONSTRAINT FK_PILOT FOREIGN KEY (PILOT_KEY) REFERENCES PILOTDIM,
		CONSTRAINT FK_AIRCRAFT FOREIGN KEY (AIRCRAFT_KEY) REFERENCES AIRCRAFTDIM

