--1 List the customers from California who bought red mountain bikes in September 2003.  Use order date as date bought

SELECT	C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, B.MODELTYPE, PA.COLORLIST, B.ORDERDATE, B.SALESTATE
FROM	BIKE..CUSTOMER C INNER JOIN BIKE..BICYCLE B ON C.CUSTOMERID = B.CUSTOMERID
		INNER JOIN BIKE..PAINT PA ON B.PAINTID = PA.PAINTID
		INNER JOIN BIKE..CITY CT ON C.CITYID = CT.CITYID
WHERE	B.MODELTYPE LIKE 'MOUNTAIN%'
		AND PA.COLORLIST = 'RED'
		AND B.ORDERDATE >= '2003-09-01' AND B.ORDERDATE <= '2003-09-30'
		AND CT.STATE = 'CA'

--2 List the employees who sold race bikes shipped to Wisconsin without the help of a retail store in 2001
--shipped to Wisconsin I'm guessing means shipped to customers who live in Wisconsin

SELECT	B.EMPLOYEEID, E.LASTNAME, B.SALESTATE, B.MODELTYPE, B.STOREID, B.ORDERDATE
FROM	BIKE..EMPLOYEE E INNER JOIN BIKE..BICYCLE B ON E.EMPLOYEEID = B.EMPLOYEEID
		INNER JOIN BIKE..CUSTOMER C ON C.CUSTOMERID = B.CUSTOMERID
		INNER JOIN BIKE..CITY CT ON C.CITYID = CT.CITYID
WHERE	B.MODELTYPE = 'RACE'
		AND CT.STATE = 'WI'
		AND YEAR(B.ORDERDATE) = '2001'
		AND B.STOREID IS NULL

--3 List all of the (distinct) rear derailleurs installed on road bikes sold in Florida in 2002.

SELECT	DISTINCT C.COMPONENTID, M.MANUFACTURERNAME, C.PRODUCTNUMBER
FROM	BIKE..COMPONENT C INNER JOIN BIKE..MANUFACTURER M ON C.MANUFACTURERID = M.MANUFACTURERID
		INNER JOIN BIKE..BIKEPARTS BP ON C.COMPONENTID = BP.COMPONENTID
		INNER JOIN BIKE..BICYCLE B ON BP.SERIALNUMBER = B.SERIALNUMBER
WHERE	C.CATEGORY = 'REAR DERAILLEUR'
		AND YEAR(BP.DATEINSTALLED) = '2002'
		AND B.MODELTYPE = 'ROAD'
		AND B.SALESTATE = 'FL'

--4 Who bought the largest (frame size) full suspension mountain bike sold in Georgia in 2004?

SELECT	DISTINCT C.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, B.MODELTYPE, B.SALESTATE, B.FRAMESIZE, B.ORDERDATE
FROM	BIKE..CUSTOMER C INNER JOIN BIKE..BICYCLE B ON C.CUSTOMERID = B.CUSTOMERID
		INNER JOIN BIKE..BIKEPARTS BP ON BP.SERIALNUMBER = B.SERIALNUMBER
		INNER JOIN BIKE..COMPONENT CP ON BP.COMPONENTID = CP.COMPONENTID
WHERE	B.SALESTATE = 'GA'
		AND B.MODELTYPE = 'MOUNTAIN FULL'
		AND B.ORDERDATE >= '2004-01-01' AND B.ORDERDATE <= '2004-12-31'
		AND B.FRAMESIZE = (SELECT	TOP 1 B.FRAMESIZE
						   FROM		BIKE..BICYCLE B
						   WHERE	B.SALESTATE = 'GA'
									AND B.MODELTYPE = 'MOUNTAIN FULL'
									AND B.ORDERDATE >= '2004-01-01' AND B.ORDERDATE <= '2004-12-31'
							ORDER BY B.FRAMESIZE DESC
							)

--5 Which manufacturer gave us the largest discount on an order in 2003?

SELECT	TOP 1 M.MANUFACTURERID, M.MANUFACTURERNAME
FROM	BIKE..PURCHASEORDER P INNER JOIN BIKE..MANUFACTURER M ON P.MANUFACTURERID = M.MANUFACTURERID
WHERE	YEAR(P.ORDERDATE) = '2003'
ORDER BY P.DISCOUNT DESC

--6 What is the most expensive road bike component we stock that has a quantity on hand greater than 200 units?

SELECT	DISTINCT CO.COMPONENTID, M.MANUFACTURERNAME, CO.PRODUCTNUMBER, CO.ROAD, CO.CATEGORY, CO.LISTPRICE, CO.QUANTITYONHAND
FROM	BIKE..COMPONENT CO INNER JOIN BIKE..MANUFACTURER M ON CO.MANUFACTURERID = M.MANUFACTURERID
		INNER JOIN BIKE..BIKEPARTS BP ON BP.COMPONENTID = CO.COMPONENTID
		INNER JOIN BIKE..BICYCLE B ON B.SERIALNUMBER = BP.SERIALNUMBER
WHERE	B.MODELTYPE = 'ROAD'
		AND CO.LISTPRICE =	(SELECT	MAX(CO.LISTPRICE) AS PRICE
							 FROM	BIKE..COMPONENT CO
							 WHERE	CO.QUANTITYONHAND > 200
								AND CO.ROAD = 'ROAD'
							)
--WORKS AS WELL, USING TOP KEYWORD

SELECT	TOP 1 CO.COMPONENTID, M.MANUFACTURERNAME, CO.PRODUCTNUMBER, CO.ROAD, CO.CATEGORY, CO.LISTPRICE, CO.QUANTITYONHAND
FROM	BIKE..COMPONENT CO INNER JOIN BIKE..MANUFACTURER M ON CO.MANUFACTURERID = M.MANUFACTURERID
		INNER JOIN BIKE..BIKEPARTS BP ON BP.COMPONENTID = CO.COMPONENTID
		INNER JOIN BIKE..BICYCLE B ON B.SERIALNUMBER = BP.SERIALNUMBER
WHERE	B.MODELTYPE = 'ROAD'
		AND CO.QUANTITYONHAND > 200
ORDER BY CO.LISTPRICE DESC
						 
--7 Which inventory item represents the most money sitting on the shelf—based on estimated cost?

SELECT	TOP 1 CO.COMPONENTID, M.MANUFACTURERNAME, CO.PRODUCTNUMBER, CO.CATEGORY, CO.YEAR, 
		(CO.QUANTITYONHAND*CO.ESTIMATEDCOST) AS VALUE
FROM	BIKE..COMPONENT CO INNER JOIN BIKE..MANUFACTURER M ON CO.MANUFACTURERID = M.MANUFACTURERID
ORDER BY CO.QUANTITYONHAND*CO.ESTIMATEDCOST DESC

--8 What is the greatest number of components ever installed in one day by one employee?

SELECT	TOP 1 BP.EMPLOYEEID, E.LASTNAME, BP.DATEINSTALLED, COUNT(BP.COMPONENTID) AS COUNTOFCOMPONENTID
FROM	BIKE..BIKEPARTS BP INNER JOIN BIKE..COMPONENT C ON BP.COMPONENTID = C.COMPONENTID
		INNER JOIN BIKE..EMPLOYEE E ON E.EMPLOYEEID = BP.EMPLOYEEID
WHERE	BP.EMPLOYEEID <> 0     -- NOT INCLUDING BLANK EMPLOYEE ENTRANTS
GROUP BY BP.EMPLOYEEID, E.LASTNAME, BP.DATEINSTALLED
ORDER BY COUNT(BP.COMPONENTID) DESC

--9 What was the most popular letter style on race bikes in 2003?

SELECT	TOP 1 B.LETTERSTYLEID, COUNT(B.SERIALNUMBER) AS COUNTOFSERIALNUMBER
FROM	BIKE..BICYCLE B
WHERE	YEAR(B.ORDERDATE) = '2003'
		AND B.MODELTYPE LIKE 'RACE%'
GROUP BY B.LETTERSTYLEID
ORDER BY COUNT(B.SERIALNUMBER) DESC

--*****10 Which customer spent the most money with us and how many bicycles did that person buy in 2002?

SELECT	TOP 1 B.CUSTOMERID, C.LASTNAME, C.FIRSTNAME, COUNT(B.SERIALNUMBER) AS [NUMBER OF BIKES],
	 SUM(B.SALEPRICE) AS [AMOUNT SPENT]
FROM	BIKE..BICYCLE B INNER JOIN BIKE..CUSTOMER C ON B.CUSTOMERID = C.CUSTOMERID
WHERE	YEAR(B.ORDERDATE) = '2002'
GROUP BY B.CUSTOMERID, C.LASTNAME, C.FIRSTNAME
ORDER BY SUM(B.SALEPRICE) DESC

--11 Have the sales of mountain bikes (full suspension or hard tail) 
--   increased or decreased from 2000 to 2004 (by count not by value)?

SELECT	YEAR(B.ORDERDATE) AS [SALE YEAR], COUNT(B.SERIALNUMBER) AS COUNTOFSERIALNUMBER
FROM	BIKE..BICYCLE B
WHERE	YEAR(B.ORDERDATE) BETWEEN '2000' AND '2004'
		AND B.MODELTYPE LIKE 'MOUNTAIN%' --BOTH TYPES OF MOUNTAIN BIKES
GROUP BY YEAR(B.ORDERDATE)
ORDER BY YEAR(B.ORDERDATE)

--12 Which component did the company spend the most money on in 2003?
--I THINK THIS ONE WORKS...
SELECT	TOP 1 P.COMPONENTID, M.MANUFACTURERNAME, CO.PRODUCTNUMBER, CO.CATEGORY, SUM(P.PRICEPAID*P.QUANTITY) AS VALUE
FROM	BIKE..COMPONENT CO INNER JOIN BIKE..PURCHASEITEM P ON P.COMPONENTID = CO.COMPONENTID
		INNER JOIN BIKE..PURCHASEORDER PO ON P.PURCHASEID = PO.PURCHASEID
		INNER JOIN BIKE..MANUFACTURER M ON PO.MANUFACTURERID = M.MANUFACTURERID
WHERE	YEAR(PO.ORDERDATE) = '2003'
GROUP BY P.COMPONENTID, M.MANUFACTURERNAME, CO.PRODUCTNUMBER, CO.CATEGORY
ORDER BY SUM(P.PRICEPAID*P.QUANTITY) DESC

--13 Which employee painted the most red race bikes in May 2003?

SELECT	E.EMPLOYEEID, E.LASTNAME, COUNT(B.SERIALNUMBER) AS [NUMBER PAINTED] -- GET TWO ANSWERS, BOTH ONLY PAINTED ONE RED RACE BIKE IN MAY 2003
FROM	BIKE..BICYCLE B INNER JOIN BIKE..EMPLOYEE E ON B.PAINTER = E.EMPLOYEEID
		INNER JOIN BIKE..PAINT P ON P.PAINTID = B.PAINTID
WHERE	P.COLORLIST = 'RED'
		AND B.MODELTYPE LIKE 'RACE%'
		AND YEAR(B.ORDERDATE) = '2003'
		AND MONTH(B.ORDERDATE) = '5'
GROUP BY E.EMPLOYEEID, E.LASTNAME

--14 Which California bike shop helped sell the most bikes (by value) in 2003?

SELECT	TOP 1 RS.STOREID, RS.STORENAME, C.CITY, SUM(B.SALEPRICE) AS SUMOFSALEPRICE
FROM	BIKE..BICYCLE B INNER JOIN BIKE..RETAILSTORE RS ON B.STOREID = RS.STOREID
		INNER JOIN BIKE..CITY C ON RS.CITYID = C.CITYID
WHERE	C.STATE = 'CA'
		AND YEAR(B.ORDERDATE) = '2003'
GROUP BY RS.STOREID, RS.STORENAME, C.CITY
ORDER BY SUM(B.SALEPRICE) DESC

--15 What is the total weight of the components on bicycle 11356?

SELECT	SUM(C.WEIGHT * BP.QUANTITY) AS TOTALWEIGHT
FROM	BIKE..BICYCLE B INNER JOIN BIKE..BIKEPARTS BP ON B.SERIALNUMBER = BP.SERIALNUMBER
		INNER JOIN BIKE..COMPONENT C ON BP.COMPONENTID = C.COMPONENTID
WHERE	B.SERIALNUMBER = '11356'

--16 What is the total list price of all items in the 2002 Campy Record groupo?

SELECT	G.GROUPNAME, SUM(C.LISTPRICE) AS SUMOFLISTPRICE
FROM	BIKE..COMPONENT C INNER JOIN BIKE..GROUPCOMPONENTS GC ON C.COMPONENTID = GC.COMPONENTID
		INNER JOIN BIKE..GROUPO G ON GC.GROUPID = G.COMPONENTGROUPID
WHERE	G.GROUPNAME IN
					 (SELECT	G.GROUPNAME
					  FROM		BIKE..GROUPO G
					  WHERE		G.GROUPNAME LIKE 'CAMPY RECORD 2002'
					 )
GROUP BY G.GROUPNAME

--17 In 2003, were more race bikes built from carbon or titanium (based on the down tube)?

SELECT	T.MATERIAL, COUNT(B.SERIALNUMBER) AS COUNTOFSERIALNUMBER
FROM	BIKE..BICYCLE B INNER JOIN BIKE..BICYCLETUBEUSAGE BT ON B.SERIALNUMBER = BT.SERIALNUMBER
		INNER JOIN BIKE..TUBEMATERIAL T ON BT.TUBEID = T.TUBEID
		INNER JOIN BIKE..BIKETUBES BS ON B.SERIALNUMBER = BS.SERIALNUMBER
WHERE	B.MODELTYPE = 'RACE'
		AND YEAR(B.ORDERDATE) = '2003'
		AND BS.TUBENAME LIKE 'DOWN'
		AND T.MATERIAL IN 
						(SELECT	MATERIAL
						 FROM	BIKE..TUBEMATERIAL 
						 WHERE	MATERIAL LIKE 'CARBON%'
						 OR		MATERIAL LIKE 'TITANIUM'
						 )
GROUP BY T.MATERIAL

--18 What is the average price paid for the 2001 Shimano XTR rear derailleurs?

SELECT	AVG(P.PRICEPAID) AS AVGOFPRICEPAID
FROM	BIKE..COMPONENT C INNER JOIN BIKE..PURCHASEITEM P ON C.COMPONENTID = P.COMPONENTID
		INNER JOIN BIKE..GROUPCOMPONENTS GP ON C.COMPONENTID = GP.COMPONENTID
		INNER JOIN BIKE..GROUPO G ON GP.GROUPID = G.COMPONENTGROUPID
WHERE	G.GROUPNAME = 'SHIMANO XTR 2001'
		AND C.CATEGORY = 'REAR DERAILLEUR'

--19 What is the average top tube length for a 54 cm (frame size) road bike built in 1999?

SELECT	AVG(B.TOPTUBE) AS AVGOFTOPTUBE
FROM	BIKE..BICYCLE B 
WHERE	B.FRAMESIZE = 54
		AND B.MODELTYPE = 'ROAD'
		AND YEAR(B.ORDERDATE) = '1999'

--20 On average, which costs (list price) more: road tires or mountain bike tires?

SELECT	C.ROAD, AVG(C.LISTPRICE) AS AVGOFLISTPRICE
FROM	BIKE..COMPONENT C
WHERE	C.CATEGORY = 'TIRE'
GROUP BY C.ROAD
ORDER BY AVG(C.LISTPRICE) DESC

--21 In May 2003, which employees sold road bikes that they also painted?

SELECT	DISTINCT B.EMPLOYEEID, E.LASTNAME
FROM	BIKE..BICYCLE B INNER JOIN BIKE..EMPLOYEE E ON B.EMPLOYEEID = E.EMPLOYEEID
WHERE	B.PAINTER = E.EMPLOYEEID
		AND B.MODELTYPE = 'ROAD'
		AND MONTH(B.ORDERDATE) = '5'
		AND YEAR(B.ORDERDATE) = '2003'

--22 In 2002, was the Old English letter style more popular with some paint jobs?

SELECT	B.PAINTID, P.COLORNAME, COUNT(B.SERIALNUMBER) AS [NUM OF BIKES PAINTED]
FROM	BIKE..BICYCLE B INNER JOIN BIKE..PAINT P ON B.PAINTID = P.PAINTID
		INNER JOIN BIKE..LETTERSTYLE L ON L.LETTERSTYLE = B.LETTERSTYLEID
WHERE	YEAR(B.ORDERDATE) = '2002'
		AND L.LETTERSTYLE = 'ENGLISH'
GROUP BY B.PAINTID, B.LETTERSTYLEID, P.COLORNAME
ORDER BY COUNT(B.SERIALNUMBER) DESC

--23 Which race bikes in 2003 sold for more than the average price of race bikes in 2002?

SELECT	B.SERIALNUMBER, B.MODELTYPE, B.ORDERDATE, B.SALEPRICE
FROM	BIKE..BICYCLE B
WHERE	B.MODELTYPE = 'RACE'
		AND YEAR(B.ORDERDATE) = '2003'
		AND B.SALEPRICE > (SELECT	AVG(SALEPRICE)
						   FROM		BIKE..BICYCLE 
						   WHERE	YEAR(ORDERDATE) = '2002'
									AND MODELTYPE = 'RACE'
						   )
ORDER BY B.SALEPRICE DESC
		
--24 Which component that had no sales (installations) in 2004 has the highest inventory value (cost basis)?

SELECT	DISTINCT TOP 1 M.MANUFACTURERNAME, C.PRODUCTNUMBER, C.CATEGORY, 
		(C.ESTIMATEDCOST * C.QUANTITYONHAND) AS VALUE, C.COMPONENTID
FROM	BIKE..COMPONENT C INNER JOIN BIKE..MANUFACTURER M ON C.MANUFACTURERID = M.MANUFACTURERID
		INNER JOIN BIKE..BIKEPARTS BP ON BP.COMPONENTID = C.COMPONENTID
WHERE	C.COMPONENTID NOT IN 
							 (SELECT	COMPONENTID
							  FROM		BIKE..BIKEPARTS
							  WHERE		YEAR(DATEINSTALLED) = '2004'
							  )
ORDER BY (C.ESTIMATEDCOST * C.QUANTITYONHAND) DESC

--25 Create a vendor contacts list of all manufacturers and retail stores in California.
-- Include only the columns for VendorName and Phone.
-- The retail stores should only include stores that participated
-- in the sale of at least one bicycle in 2004

SELECT	M.MANUFACTURERNAME AS VENDORNAME, M.PHONE AS PHONE
FROM	BIKE..MANUFACTURER M INNER JOIN BIKE..CITY CT ON M.CITYID = CT.CITYID
WHERE	CT.STATE = 'CA'
UNION ALL
SELECT	RS.STORENAME AS VENDORNAME, RS.PHONE AS PHONE
FROM	BIKE..RETAILSTORE RS INNER JOIN BIKE..CITY CT ON RS.CITYID = CT.CITYID
WHERE	CT.STATE = 'CA'
		AND RS.STOREID IN 
						(SELECT	DISTINCT STOREID
						 FROM	BIKE..BICYCLE B
						 WHERE	YEAR(ORDERDATE) = '2004'
						 )

--26 List all of the employees who report to Venetiaan.

--SELF JOINING
SELECT	E1.LASTNAME AS MANAGER, E2.EMPLOYEEID, E2.LASTNAME, E2.FIRSTNAME, E2.TITLE
FROM	BIKE..EMPLOYEE E1 INNER JOIN BIKE..EMPLOYEE E2 ON E1.EMPLOYEEID = E2.CURRENTMANAGER
WHERE	E1.LASTNAME = 'VENETIAAN'

--27  List the components where the company 
-- purchased at least 25 percent more units than it used through June 30, 2000.

SELECT	DISTINCT C.COMPONENTID, M.MANUFACTURERNAME, C.PRODUCTNUMBER, C.CATEGORY, SUM(P.QUANTITYRECEIVED) AS TOTALRECEIVED,
		SUM(BP.QUANTITY) AS TOTALUSED, (SUM(P.QUANTITYRECEIVED)-SUM(BP.QUANTITY)) AS NETGAIN, 
		((SUM(P.QUANTITYRECEIVED)-SUM(BP.QUANTITY))/SUM(BP.QUANTITY)) AS NETPCT, C.LISTPRICE
FROM	BIKE..BIKEPARTS BP INNER JOIN BIKE..COMPONENT C ON BP.COMPONENTID = C.COMPONENTID
		INNER JOIN BIKE..MANUFACTURER M ON C.MANUFACTURERID = M.MANUFACTURERID
		INNER JOIN BIKE..PURCHASEITEM P ON C.COMPONENTID = P.COMPONENTID
WHERE	C.COMPONENTID IN
						(SELECT	COMPONENTID
						 FROM	BIKE..PURCHASEITEM P INNER JOIN BIKE..PURCHASEORDER PO ON P.PURCHASEID = PO.PURCHASEID
						 WHERE	PO.ORDERDATE < '2000-07-01'
						 )
		AND C.COMPONENTID IN
							(SELECT	COMPONENTID
							 FROM	BIKE..BIKEPARTS
							 WHERE	DATEINSTALLED < '2000-07-01'
							 )
GROUP BY C.COMPONENTID, M.MANUFACTURERNAME, C.PRODUCTNUMBER, C.CATEGORY, C.LISTPRICE
HAVING	((SUM(P.QUANTITYRECEIVED)-SUM(BP.QUANTITY))/SUM(BP.QUANTITY)) >= 25

--28 In which years did the average build time for the year exceed the overall average 
-- build time for all years?  The build time is the difference between order date and ship date.

SELECT	YEAR(B.ORDERDATE) AS YEAR, AVG(DATEDIFF(SECOND,B.ORDERDATE,B.SHIPDATE)/3600.0) AS BUILDTIMEINHRS
FROM	BIKE..BICYCLE B
GROUP BY YEAR(B.ORDERDATE)
HAVING	AVG(DATEDIFF(SECOND,B.ORDERDATE,B.SHIPDATE)/3600.0)>
															(SELECT	AVG(BUILDTIMEINHRS)
															 FROM	(SELECT	YEAR(B.ORDERDATE) AS YEAR, 
																			AVG(DATEDIFF(SECOND,B.ORDERDATE,B.SHIPDATE)/3600.0)
																			AS BUILDTIMEINHRS
																	 FROM	BIKE..BICYCLE B
																	 GROUP BY YEAR(B.ORDERDATE)) B
															 )
ORDER BY YEAR(B.ORDERDATE)
