
CREATE OR ALTER	TRIGGER [dbo].[A8]
	ON	[dbo].[DETAILRENTAL]
	AFTER UPDATE
AS 
BEGIN
	SELECT 'THE ROW BEFORE IT WAS UPDATED'
	SELECT	*	FROM	DELETED

	SELECT 'THE ROW AFTER IT WAS UPDATED'
	SELECT	*	FROM	INSERTED 

	DECLARE @LATEFEEPRIOR DECIMAL (10,2)
	DECLARE @LATEFEEAFTER DECIMAL (10,2)
	DECLARE @AMOUNT DECIMAL(10,2)
	DECLARE @RENT_NUM INT
	DECLARE @OLDDETAIL_DUEDATE DATE
	DECLARE	@NEWDETAIL_DUEDATE DATE
	DECLARE @OLDDETAIL_RETURNDATE DATE
	DECLARE @NEWDETAIL_RETURNDATE DATE
	DECLARE @DETAIL_DAILYLATEFEE DECIMAL

	
	--UPDATE CASE
	IF(EXISTS (SELECT * FROM INSERTED) AND EXISTS(SELECT * FROM DELETED))
	BEGIN
	--LOGIC TO HANDLE RECORDS IN UPDATE CASE
		DECLARE UPDATE_CURSOR CURSOR FOR
		SELECT	I.RENT_NUM, DATEDIFF(DAY,I.DETAIL_DUEDATE, I.DETAIL_RETURNDATE)*I.DETAIL_DAILYLATEFEE AS LATEFEEAFTER,
			DATEDIFF(DAY, D.DETAIL_DUEDATE, D.DETAIL_RETURNDATE)*I.DETAIL_DAILYLATEFEE AS LATEFEEPRIOR
		FROM	INSERTED I INNER JOIN DELETED D ON D.RENT_NUM = I.RENT_NUM AND D.VID_NUM = I.VID_NUM

		OPEN	UPDATE_CURSOR
		FETCH	NEXT FROM UPDATE_CURSOR
				INTO @RENT_NUM, @LATEFEEAFTER, @LATEFEEPRIOR
		
		
		--ITS ADDING PAST AMOUNT TO BALANCE FOR WHATEVER REASON
		WHILE(@@FETCH_STATUS = 0)
		BEGIN
	

		SET	@AMOUNT = @LATEFEEAFTER - @LATEFEEPRIOR

		IF(@AMOUNT <> 0)
		BEGIN
		UPDATE	MEMBERSHIP 
		SET	MEM_BALANCE = MEM_BALANCE + @AMOUNT
		WHERE	MEM_NUM IN (SELECT	MEM_NUM
							FROM	RENTAL
							WHERE	RENT_NUM = @RENT_NUM
							)
		END
		FETCH NEXT FROM UPDATE_CURSOR
				INTO @RENT_NUM, @LATEFEEAFTER, @LATEFEEPRIOR			
			END
			CLOSE	UPDATE_CURSOR
			DEALLOCATE UPDATE_CURSOR
	END
END

-----------------------Test Data------------------------------
--BASE DATA TO START
SELECT * FROM MEMBERSHIP
SELECT * FROM DETAILRENTAL

--UPDATE RENT NUMS 1006
UPDATE	DETAILRENTAL
SET		DETAIL_DUEDATE = '2013-03-06 00:00:00.000'
WHERE	RENT_NUM = 1006

--CHECK DATA AFTER UPDATE
SELECT * FROM MEMBERSHIP
SELECT * FROM DETAILRENTAL

--SETTING MEMBERSHIP BALANCE BACK TO 0
UPDATE	MEMBERSHIP
SET		MEM_BALANCE = 0
WHERE	MEM_NUM = 107

--CHANGE DATA AGAIN FOR RETURNDATE
UPDATE	DETAILRENTAL
SET		DETAIL_RETURNDATE = '2013-03-07 00:00:00.000'
WHERE	RENT_NUM = 1007

--CHANGE DATA BACK TO NULL
UPDATE	DETAILRENTAL
SET		DETAIL_RETURNDATE = NULL
WHERE	RENT_NUM = 1007



